apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  namespace: priyanshi-ns
spec:
  replicas: 3
  selector: 
    matchLabels:
      lable: deploy
  template:
    metadata:
      name: priya-pod 
      namespace: priyanshi-ns
      labels:
        lable: deploy
    spec:
      containers:
      - image: nginx:stable-perl
        name: nginx-container
        ports:
        - containerPort: 80


           

    